# Generated by Django 4.2.5 on 2023-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data contacao')),
                ('moeda', models.CharField(max_length=3)),
                ('moeda_base', models.CharField(max_length=3)),
                ('cotacao', models.FloatField()),
            ],
        ),
    ]
